rest/urls.py
from django.urls import include, path
from rest_framework import routers
from rest import views

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('farms', views.FarmsViewSet)



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
]

swmif/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='landing'),
    path('user/',include('user.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest/', include('rest.urls')),
]


urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farm/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
import datetime
import os
import random
from PIL import Image

from user.models import Address
from crop.models import Crop


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_file_path(instance, filename):
    new_filename = random.randint(1, 3231546414654785)
    name, ext =get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "posts/{new_filename}/{final_filename}".format(new_filename=new_filename, final_filename=final_filename)


class Soil(models.Model):
    name        = models.CharField(max_length=255)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class WaterResource(models.Model):
    PRIMARY = 1
    SECONDARY = 2
    TYPE_CHOICES = (
        (PRIMARY, 'Primary'),
        (SECONDARY, 'Secondary'),
    )

    owner           = models.ForeignKey(User, on_delete=models.CASCADE)
    volume          = models.IntegerField() #in liters
    depth           = models.IntegerField() #in feets
    diameter        = models.IntegerField() #in feets
    income_rate     = models.IntegerField() #liter per minute
    available_water = models.IntegerField() #in liter
    type            = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, default=1)
    is_active       = models.BooleanField(default=False)
    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Owner - ' + str(self.owner.first_name) + ' ' + str(self.owner.last_name) + ' - ' + str(self.volume) + ' Litres'

class Farm(models.Model):
    owner           = models.ForeignKey(User, on_delete=models.CASCADE)
    soil            = models.ForeignKey(Soil, on_delete=models.DO_NOTHING)
    location        = models.ForeignKey(Address, on_delete=models.DO_NOTHING)
    water_resource  = models.ForeignKey(WaterResource, on_delete=models.DO_NOTHING)
    area            = models.DecimalField(default=000.0, max_digits=300, decimal_places=2)
    is_active       = models.BooleanField(default=False)
    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Owner - ' + str(self.owner.first_name) + ' ' + str(self.owner.last_name) + ' Area - ' + str(self.area) + ' Acres.'


class Plots(models.Model):
    FULL = 1
    HALF = 2
    AREA_CHOICES = (
        (FULL, 'Full'),
        (HALF, 'Half'),
    )
    farm            = models.ForeignKey(Farm, on_delete=models.CASCADE)
    area            = models.PositiveSmallIntegerField(choices=AREA_CHOICES , default=1)
    is_active       = models.BooleanField(default=True)
    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Owner - ' + str(self.farm.owner.first_name) + ' ' + str(self.farm.owner.last_name) + ' - ' + str(self.area) + ' Acres.'


class Ploting(models.Model):
    plot            = models.ForeignKey(Plots, on_delete=models.CASCADE)
    crop            = models.ForeignKey(Crop, on_delete=models.CASCADE)
    is_active       = models.BooleanField(default=True)
    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Plotted  - ' + str(self.crop.name) + ' on  ' + str(self.created) + ' at ' + str(self.plot)


class Reports(models.Model):
    added_by        = models.ForeignKey(User, on_delete=models.CASCADE)
    ploting         = models.ForeignKey(Ploting, on_delete=models.CASCADE)
    file            = models.ImageField(upload_to=upload_file_path)
    remark          = models.CharField(max_length=255, null=True, blank=True)
    created         = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Report for  - ' + str(self.ploting.crop) + ' is added by ' + str(self.added_by)

templates/site/dashboard/add_plot.html
{% extends 'site/base.html' %}
{% load static %}
{% block content %}
{% include 'partials/header.html' %}
{% include 'partials/aside.html' %}
  <!-- .app-main -->
  <main class="app-main">
    <!-- .wrapper -->
    <div class="wrapper">
      <!-- .page -->
      <div class="page">
        <!-- .page-inner -->
        <div class="page-inner">
          <!-- .page-title-bar -->
          <header class="page-title-bar">
            <div class="d-flex flex-column flex-md-row">
              <p class="lead">
                <span class="font-weight-bold">Hi, {{ user.first_name }} {{ user.last_name }}.</span> <span class="d-block text-muted"> {{ cord }} Here’s what’s happening with your farm today.</span>
              </p>
              <div class="ml-auto" hidden="hidden">
                <!-- .dropdown -->
                <div class="dropdown">
                  <button class="btn btn-secondary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>This Week</span> <i class="fa fa-fw fa-caret-down"></i></button> <!-- .dropdown-menu -->
                  <div class="dropdown-menu dropdown-menu-right dropdown-menu-md stop-propagation">
                    <div class="dropdown-arrow"></div><!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpToday" name="dpFilter" data-start="2019/03/27" data-end="2019/03/27"> <label class="custom-control-label d-flex justify-content-between" for="dpToday"><span>Today</span> <span class="text-muted">Mar 27</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpYesterday" name="dpFilter" data-start="2019/03/26" data-end="2019/03/26"> <label class="custom-control-label d-flex justify-content-between" for="dpYesterday"><span>Yesterday</span> <span class="text-muted">Mar 26</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpWeek" name="dpFilter" data-start="2019/03/21" data-end="2019/03/27" checked> <label class="custom-control-label d-flex justify-content-between" for="dpWeek"><span>This Week</span> <span class="text-muted">Mar 21-27</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpMonth" name="dpFilter" data-start="2019/03/01" data-end="2019/03/27"> <label class="custom-control-label d-flex justify-content-between" for="dpMonth"><span>This Month</span> <span class="text-muted">Mar 1-31</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpYear" name="dpFilter" data-start="2019/01/01" data-end="2019/12/31"> <label class="custom-control-label d-flex justify-content-between" for="dpYear"><span>This Year</span> <span class="text-muted">2019</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpCustom" name="dpFilter" data-start="2019/03/27" data-end="2019/03/27"> <label class="custom-control-label" for="dpCustom">Custom</label>
                      <div class="custom-control-hint my-1">
                        <!-- datepicker:range -->
                        <input type="text" class="form-control" id="dpCustomInput" data-toggle="flatpickr" data-mode="range" data-disable-mobile="true" data-date-format="Y-m-d"> <!-- /datepicker:range -->
                      </div>
                    </div><!-- /.custom-control -->
                  </div><!-- /.dropdown-menu -->
                </div><!-- /.dropdown -->
              </div>
            </div>
          </header><!-- /.page-title-bar -->


          <!-- .page-inner -->
          <div class="page-inner">
            <!-- .page-section -->
            <div class="page-section">
              <!-- .card -->
              <div class="card card-fluid">
                <!-- .card-body -->
                <div class="card-body">
                  <!-- .form-group -->
                  <div class="form-group" hidden="hidden">
                    <!-- .input-group -->
                    <div class="input-group input-group-alt">
                      <!-- .input-group-prepend -->
                      <div class="input-group-prepend">
                        <select id="filterBy" class="custom-select">
                          <option value='' selected> Filter By </option>
                          <option value="1"> Line </option>
                          <option value="2"> Village </option>
                          <option value="3"> City </option>
                          <option value="4"> District </option>
                          <option value="5"> State </option>
                        </select>
                      </div><!-- /.input-group-prepend -->
                      <!-- .input-group -->
                      <div class="input-group has-clearable">
                        <button id="clear-search" type="button" class="close" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle"></i></span></button>
                        <div class="input-group-prepend">
                          <span class="input-group-text"><span class="oi oi-magnifying-glass"></span></span>
                        </div><input id="table-search" type="text" class="form-control" placeholder="Search products">
                      </div><!-- /.input-group -->
                    </div><!-- /.input-group -->
                  </div><!-- /.form-group -->
                  <!-- .table -->
                  <table id="myTable" class="table">
                    <!-- thead -->
                    <thead>
                      <tr>
                        <th colspan="2" style="min-width: 320px;">
                          Details
                        </th>
                        <th> Farm </th>
                        <th> Area </th>
                        
                        <th style="width:100px; min-width:100px;"> &nbsp; </th>
                      </tr>
                    </thead><!-- /thead -->
                    <!-- tbody -->
                    <tbody>
                      <!-- create empty row to passing html validator -->
                      {% for obj in objects %}
                      <tr>
                        
                        <td></td>
                        <td>{{ obj }}</td>
                        <td>{{ obj.farm }}</td>
                        <td>{{ obj.get_area_display }}</td>
                        
                      </tr>
                      {% endfor %}
                    </tbody><!-- /tbody -->
                  </table><!-- /.table -->
                </div><!-- /.card-body -->
              </div><!-- /.card -->
              <hr class="my-5">
              
            </div><!-- /.page-section -->
          </div><!-- /.page-inner -->

          <div class="page-inner">
            
            <!-- .page-section -->
            <div class="page-section">
              <!-- grid row -->
              <div class="row">
                <!-- grid column -->
                <div class="col-lg-10">
                  <!-- .card -->
                  <div class="card card-fluid">
                    <h6 class="card-header"> Add Plot </h6><!-- .card-body -->
                    <div class="card-body">
                      <!-- form -->
                      <form method="POST" action="{% url 'add_plot' %}">{% csrf_token %}
                        <!-- form row -->
                        <div class="form-row">
                          <!-- form column -->
                          <div class="col-md-6 mb-3">
                            <label for="input01">Farm</label> {{ form.farm }}
                          </div><!-- /form column -->
                          <!-- form column -->
                          <div class="col-md-6 mb-3">
                            <label for="input02">Area</label> {{ form.area }}
                          </div><!-- /form column -->
                        </div><!-- /form row -->
                     
                        <hr>
                        <!-- .form-actions -->
                        <div class="form-actions">
                          <!-- enable submit btn when user type their current password -->
                          <button type="submit" class="btn btn-primary text-nowrap ml-auto">Add Plot</button>
                        </div><!-- /.form-actions -->
                      </form><!-- /form -->
                    </div><!-- /.card-body -->
                  </div><!-- /.card -->
                </div><!-- /grid column -->
              </div><!-- /grid row -->
            </div><!-- /.page-section -->
          </div><!-- /.page-inner -->

        </div><!-- /.page-inner -->
      </div><!-- /.page -->
    </div><!-- .app-footer -->
    <footer class="app-footer">
      <ul class="list-inline">
        <li class="list-inline-item">
          <a class="text-muted" href="#">Support</a>
        </li>
        <li class="list-inline-item">
          <a class="text-muted" href="#">Help Center</a>
        </li>
        <li class="list-inline-item">
          <a class="text-muted" href="#">Privacy</a>
        </li>
        <li class="list-inline-item">
          <a class="text-muted" href="#">Terms of Service</a>
        </li>
      </ul>
      <div class="copyright"> Copyright © 2020. All right reserved. </div>
    </footer><!-- /.app-footer -->
    <!-- /.wrapper -->
  </main><!-- /.app-main -->
{% endblock %}

templates/site/dashboard/add_water_resource.html
{% extends 'site/base.html' %}
{% load static %}
{% block content %}
{% include 'partials/header.html' %}
{% include 'partials/aside.html' %}
  <!-- .app-main -->
  <main class="app-main">
    <!-- .wrapper -->
    <div class="wrapper">
      <!-- .page -->
      <div class="page">
        <!-- .page-inner -->
        <div class="page-inner">
          <!-- .page-title-bar -->
          <header class="page-title-bar">
            <div class="d-flex flex-column flex-md-row">
              <p class="lead">
                <span class="font-weight-bold">Hi, {{ user.first_name }} {{ user.last_name }}.</span> <span class="d-block text-muted"> {{ cord }} Here’s what’s happening with your farm today.</span>
              </p>
              <div class="ml-auto" hidden="hidden">
                <!-- .dropdown -->
                <div class="dropdown">
                  <button class="btn btn-secondary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>This Week</span> <i class="fa fa-fw fa-caret-down"></i></button> <!-- .dropdown-menu -->
                  <div class="dropdown-menu dropdown-menu-right dropdown-menu-md stop-propagation">
                    <div class="dropdown-arrow"></div><!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpToday" name="dpFilter" data-start="2019/03/27" data-end="2019/03/27"> <label class="custom-control-label d-flex justify-content-between" for="dpToday"><span>Today</span> <span class="text-muted">Mar 27</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpYesterday" name="dpFilter" data-start="2019/03/26" data-end="2019/03/26"> <label class="custom-control-label d-flex justify-content-between" for="dpYesterday"><span>Yesterday</span> <span class="text-muted">Mar 26</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpWeek" name="dpFilter" data-start="2019/03/21" data-end="2019/03/27" checked> <label class="custom-control-label d-flex justify-content-between" for="dpWeek"><span>This Week</span> <span class="text-muted">Mar 21-27</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpMonth" name="dpFilter" data-start="2019/03/01" data-end="2019/03/27"> <label class="custom-control-label d-flex justify-content-between" for="dpMonth"><span>This Month</span> <span class="text-muted">Mar 1-31</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpYear" name="dpFilter" data-start="2019/01/01" data-end="2019/12/31"> <label class="custom-control-label d-flex justify-content-between" for="dpYear"><span>This Year</span> <span class="text-muted">2019</span></label>
                    </div><!-- /.custom-control -->
                    <!-- .custom-control -->
                    <div class="custom-control custom-radio">
                      <input type="radio" class="custom-control-input" id="dpCustom" name="dpFilter" data-start="2019/03/27" data-end="2019/03/27"> <label class="custom-control-label" for="dpCustom">Custom</label>
                      <div class="custom-control-hint my-1">
                        <!-- datepicker:range -->
                        <input type="text" class="form-control" id="dpCustomInput" data-toggle="flatpickr" data-mode="range" data-disable-mobile="true" data-date-format="Y-m-d"> <!-- /datepicker:range -->
                      </div>
                    </div><!-- /.custom-control -->
                  </div><!-- /.dropdown-menu -->
                </div><!-- /.dropdown -->
              </div>
            </div>
          </header><!-- /.page-title-bar -->


          <!-- .page-inner -->
          <div class="page-inner">
            <!-- .page-section -->
            <div class="page-section">
              <!-- .card -->
              <div class="card card-fluid">
                <!-- .card-body -->
                <div class="card-body">
                  <!-- .form-group -->
                  <div class="form-group" hidden="hidden">
                    <!-- .input-group -->
                    <div class="input-group input-group-alt">
                      <!-- .input-group-prepend -->
                      <div class="input-group-prepend">
                        <select id="filterBy" class="custom-select">
                          <option value='' selected> Filter By </option>
                          <option value="1"> Line </option>
                          <option value="2"> Village </option>
                          <option value="3"> City </option>
                          <option value="4"> District </option>
                          <option value="5"> State </option>
                        </select>
                      </div><!-- /.input-group-prepend -->
                      <!-- .input-group -->
                      <div class="input-group has-clearable">
                        <button id="clear-search" type="button" class="close" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle"></i></span></button>
                        <div class="input-group-prepend">
                          <span class="input-group-text"><span class="oi oi-magnifying-glass"></span></span>
                        </div><input id="table-search" type="text" class="form-control" placeholder="Search products">
                      </div><!-- /.input-group -->
                    </div><!-- /.input-group -->
                  </div><!-- /.form-group -->
                  <!-- .table -->
                  <table id="myTable" class="table">
                    <!-- thead -->
                    <thead>
                      <tr>
                        <th colspan="2" style="min-width: 320px;">
                          Water Resource
                        </th>
                        <th> Volume </th>
                        <th> Income Rate </th>
                        <th> Available Water </th>
                        <th> Type </th>
                        <th style="width:100px; min-width:100px;"> &nbsp; </th>
                      </tr>
                    </thead><!-- /thead -->
                    <!-- tbody -->
                    <tbody>
                      <!-- create empty row to passing html validator -->
                      {% for obj in objects %}
                      <tr>
                        
                        <td></td>
                        <td>{{ obj }}</td>
                        <td>{{ obj.volume }}</td>
                        <td>{{ obj.income_rate }}</td>
                        <td>{{ obj.available_water }}</td>
                        <td>{{ obj.get_type_display }}</td>
                      </tr>
                      {% endfor %}
                    </tbody><!-- /tbody -->
                  </table><!-- /.table -->
                </div><!-- /.card-body -->
              </div><!-- /.card -->
              <hr class="my-5">
              
            </div><!-- /.page-section -->
          </div><!-- /.page-inner -->


          <div class="page-inner">
            
            <!-- .page-section -->
            <div class="page-section">
              <!-- grid row -->
              <div class="row">
                <!-- grid column -->
                <div class="col-lg-12">
                  <!-- .card -->
                  <div class="card card-fluid">
                    <h6 class="card-header"> Add Water Resource </h6><!-- .card-body -->
                    <div class="card-body">
                      <!-- form -->
                      <form method="POST" action="{% url 'add_water_resource' %}">{% csrf_token %}
                        <!-- form row -->
                        <div class="form-row">
                          <!-- form column -->
                          <div class="col-md-6 mb-3">
                            <label for="input01">Volume</label> {{ form.volume }}
                          </div><!-- /form column -->
                          <!-- form column -->
                          <div class="col-md-6 mb-3">
                            <label for="input02">Depth</label> {{ form.depth }}
                          </div><!-- /form column -->
                        </div><!-- /form row -->
                        <!-- .form-group -->
                        <div class="form-group">
                          <label for="input03">Diameter</label> {{ form.diameter }}
                        </div><!-- /.form-group -->
                        <!-- .form-group -->
                        <div class="form-group">
                          <label for="input04">Available Water</label> {{ form.available_water }}
                        </div><!-- /.form-group -->
                        
                        <!-- .form-group -->
                        <div class="form-group">
                            <label for="input05">Income Rate</label> {{ form.income_rate }}
                          </div><!-- /.form-group -->
                        <hr>
                        <!-- .form-actions -->
                        <div class="form-actions">
                          <!-- enable submit btn when user type their current password -->
                          {{ form.type }}
                          <button type="submit" class="btn btn-primary text-nowrap ml-auto">Add Address</button>
                        </div><!-- /.form-actions -->
                      </form><!-- /form -->
                    </div><!-- /.card-body -->
                  </div><!-- /.card -->
                </div><!-- /grid column -->
              </div><!-- /grid row -->
            </div><!-- /.page-section -->
          </div><!-- /.page-inner -->

        </div><!-- /.page-inner -->
      </div><!-- /.page -->
    </div><!-- .app-footer -->
    <footer class="app-footer">
      <ul class="list-inline">
        <li class="list-inline-item">
          <a class="text-muted" href="#">Support</a>
        </li>
        <li class="list-inline-item">
          <a class="text-muted" href="#">Help Center</a>
        </li>
        <li class="list-inline-item">
          <a class="text-muted" href="#">Privacy</a>
        </li>
        <li class="list-inline-item">
          <a class="text-muted" href="#">Terms of Service</a>
        </li>
      </ul>
      <div class="copyright"> Copyright © 2020. All right reserved. </div>
    </footer><!-- /.app-footer -->
    <!-- /.wrapper -->
  </main><!-- /.app-main -->
{% endblock %}